services:
  # default realization for RequestDecoderInterface
  StasPlov\DtoValidatorBundle\RequestDecoder\RequestDecoder: ~
  StasPlov\DtoValidatorBundle\RequestDecoder\RequestDecoderInterface: '@StasPlov\DtoValidatorBundle\RequestDecoder\RequestDecoder'

  stas_plov_dto_validator_bundle.controller_listener:
    class: 'StasPlov\DtoValidatorBundle\EventListener\ControllerListener'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 250 }
      #- { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    arguments:
      $logger: '@logger'
      $requestDecoder: '@?StasPlov\DtoValidatorBundle\RequestDecoder\RequestDecoder'
      $validator: '@?validator'